#!/bin/sh



infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.rs
/usr/bin/rustc -o /tmp/code /tmp/code.rs

if [ -s /dev/stdin ]; then
  cat - | /tmp/code
else
  /tmp/code
fi

rm /tmp/code.rs /tmp/code
