#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.rs
/usr/bin/rustc -o /tmp/code /tmp/code.rs

if [ -s /dev/stdin ]; then
  cat - | /tmp/code
else
  /tmp/code
fi

rm /tmp/code.rs /tmp/code
