#!/bin/sh



# All Stuck code should have prefix .stk
infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.stk
cd ~/stuck/

if [ -s /dev/stdin ]; then
  cat - | /usr/bin/python stuck.py /tmp/code.stk
else
  /usr/bin/python stuck.py /tmp/code.stk
fi

rm /tmp/code.stk
