#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

# All Stuck code should have prefix .stk
infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.stk
cd ~/stuck/

if [ -s /dev/stdin ]; then
  cat - | /usr/bin/python stuck.py /tmp/code.stk
else
  /usr/bin/python stuck.py /tmp/code.stk
fi

rm /tmp/code.stk
