#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
cd ~/arcyou

if [ -p /dev/stdin ]; then
  cat - | LANG=en_US.UTF8 /usr/bin/python3 arc.py "$infile"
else
  LANG=en_US.UTF8 /usr/bin/python3 arc.py "$infile"
fi
