#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

if [ -s /dev/stdin ]; then
  cat - | /usr/bin/ag_launcher -i /usr/bin/make -f "$1"
else
  /usr/bin/ag_launcher -i /usr/bin/make -f "$1" STDIN=
fi
