#!/bin/sh

cat /root/io_header.v "$1" /root/tail.v > /tmp/Main.v

cd /tmp
rocq compile Main.v 1>&2

echo 'let () = main ()' >> main.ml
[ -f main.mli ] && ocamlopt main.mli 1>&2
ocamlopt main.ml -o prog 1>&2
./prog

rm -rf /tmp/*
