#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.matl
cd ~/MATL

if [ -p /dev/stdin ]; then
  cat - | /usr/bin/octave --path ~/MATL --eval "matl -of /tmp/code.matl"
else
  /usr/bin/octave --path ~/MATL --eval "matl -of /tmp/code.matl"
fi
