#!/bin/sh



infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.matl
cd ~/MATL

if [ -s /dev/stdin ]; then
  cat - | /usr/bin/octave --path ~/MATL --eval "matl -of /tmp/code.matl"
else
  /usr/bin/octave --path ~/MATL --eval "matl -of /tmp/code.matl"
fi
