#!/bin/sh



infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.cs
mcs /tmp/code.cs

if [ -s /dev/stdin ]; then
  cat - | mono /tmp/code.exe
else
  mono /tmp/code.exe
fi

rm /tmp/code.cs /tmp/code.exe
