#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.cs
mcs /tmp/code.cs

if [ -s /dev/stdin ]; then
  cat - | mono /tmp/code.exe
else
  mono /tmp/code.exe
fi

rm /tmp/code.cs /tmp/code.exe
