#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

/usr/bin/python3 ~/seed.py "$1" > /tmp/code.b98

if [ -p /dev/stdin ]; then
  cat - | ~/cfunge /tmp/code.b98
else
  ~/cfunge /tmp/code.b98
fi

rm /tmp/code.b98
