#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

if [ -p /dev/stdin ]; then
  input=$(cat -)
  /usr/bin/node ~/beam-cli.js "$1" "$input"
else
  /usr/bin/node ~/beam-cli.js "$1"
fi
