#!/bin/sh

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.c
gcc -O2 -std=c23 -fpermissive -Wno-error -Wno-implicit -Wno-int-conversion -w /tmp/code.c -o /tmp/code -lm

cat - | /tmp/code

rm /tmp/code.c /tmp/code
