#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.c
gcc -Wall -O2 -std=c99 /tmp/code.c -o /tmp/code -lm

if [ -p /dev/stdin ]; then
  cat - | /tmp/code
else
  /tmp/code
fi

rm /tmp/code.c /tmp/code
