#!/bin/bash

# All Emojicode code should have prefix .emojic
infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.emojic
/usr/local/bin/emojicodec /tmp/code.emojic

cat - | /tmp/code

rm /tmp/code /tmp/code.emojic
