#!/bin/sh



# All Emojicode code should have prefix .emojic
infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.emojic
~/Emojicode/bin/emojicodec /tmp/code.emojic

cat - | ~/Emojicode/bin/emojicode /tmp/code.emojib

rm /tmp/code.emojic /tmp/code.emojib
