#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
cp -sf "$infile" /tmp/code.mid
cd /tmp
mono ~/Velato/Rottytooth.Esolang.Velato/bin/Release/Velato.exe -C code.mid 1> /dev/null

if [ -s /dev/stdin ]; then
  cat - | mono code.mid.exe
else
  mono code.mid.exe
fi

rm /tmp/code.mid /tmp/code.mid.mdb
