#!/bin/sh

infile=$(realpath "$1")
cp -sf "$infile" /tmp/code.mid
cd /tmp
mono ~/Velato/Rottytooth.Esolang.Velato/bin/Release/Velato.exe -C code.mid 1> /dev/null

cat - | mono code.mid.exe

rm /tmp/code.mid /tmp/code.mid.mdb
