#!/bin/sh



infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.arnoidc
cd /tmp
/usr/bin/java -jar ~/ArnoldC.jar code.arnoidc

if [ -s /dev/stdin ]; then
  cat - | /usr/bin/java code
else
  /usr/bin/java code
fi

rm /tmp/code.arnoidc /tmp/code.class
