#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.nako3
cd /tmp

if [ -s /dev/stdin ]; then
  cat - | /usr/bin/cnako3 "$1"
else
  /usr/bin/cnako3 "$1"
fi

rm /tmp/code.nako3