#!/bin/sh



if [ -s /dev/stdin ]; then
  input=$(cat -)

  if [ -z "$input" ]; then
    # At least one newline is required
    echo '' | /usr/bin/jq -rR -f "$1"
  else
    echo -n "$input" | /usr/bin/jq -rR -f "$1"
  fi
else
  # At least one newline is required
  echo '' | /usr/bin/jq -rR -f "$1"
fi
