#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

if [ -s /dev/stdin ]; then
  input=$(cat -)

  if [ -z "$input" ]; then
    # At least one newline is required
    echo '' | /usr/bin/jq -rR -f "$1"
  else
    echo -n "$input" | /usr/bin/jq -rR -f "$1"
  fi
else
  # At least one newline is required
  echo '' | /usr/bin/jq -rR -f "$1"
fi
