#!/bin/sh

# Note: DO NOT LISTEN TO out.pcm, IT MAY CONTAIN UNEXPECTEDLY LOUD SOUNDS, AND MAY CAUSE EAR DAMAGE.

cat - > /tmp/in.pcm
cd /tmp/
cat "$1" | xargs /usr/bin/ffmpeg-original
cat out.pcm

rm -f /tmp/in.pcm /tmp/out.pcm
