#!/bin/sh

if ! [ -e /root/script ]; then
  echo "esolang-box: [ERROR] Language script not found" >&2
  exit 1
fi

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 [-d] <file>" >&2
  exit 1
fi

if [ "$#" = 2 ] && [ "$1" = "-d" ] && [ -e "$2" ]; then
  if ! [ -e /root/disasm ]; then
    echo "esolang-box: [ERROR] Disassembly is not supported for this language" >&2
    exit 1
  fi
  /bin/sh /root/disasm "$2"
  exit 0
fi

if [ -e /dev/stdin ]; then
  if [ -z "$STRACE_OUTPUT_PATH" ]; then
    cat - | /bin/sh /root/script "$1"
  else
    cat - | strace -f -q -o "$STRACE_OUTPUT_PATH" -e trace=execve,execveat /bin/sh /root/script "$1"
  fi
else
  if [ -z "$STRACE_OUTPUT_PATH" ]; then
    echo -n "" | /bin/sh /root/script "$1"
  else
    echo -n "" | strace -f -q -o "$STRACE_OUTPUT_PATH" -e trace=execve,execveat /bin/sh /root/script "$1"
  fi
fi
