#!/bin/sh



infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.mid
cd /tmp && ~/fugue code.mid /coffc > /dev/null
sed -i 's/\b__cdecl\b//' /tmp/code_wrp.c
sed -i 's/\bfugue\b/_fugue/' /tmp/code_wrp.c
gcc /tmp/code.obj /tmp/code_wrp.c -o /tmp/code -m32

cat - | /tmp/code

rm /tmp/code.mid /tmp/code.obj /tmp/code_wrp.c /tmp/code
