#!/bin/sh

infile=$(realpath "$1")
ln -s "$infile" /tmp/code.egi

# due to esolang-box's specification, move original egison to egison-interpreter
cat - | /usr/bin/egison-interpreter /tmp/code.egi
rm -f /tmp/code.egi
