#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

code=`cat "$1"`

if [ -s /dev/stdin ]; then
  cat - | perl ~/element.plx "$code"
else
  perl ~/element.plx "$code"
fi
