#!/bin/sh

infile=$(realpath "$1")
cd ~/Spl && /usr/bin/python3 splc.py "$infile" > /tmp/code.c

ln -sf ~/Spl/include /tmp/include
gcc -O2 -Wall /tmp/code.c -o /tmp/code -lm -lbsd

cat - | /tmp/code

rm /tmp/code.c /tmp/code /tmp/include
