#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
cd ~/Spl && /usr/bin/python3 splc.py "$infile" > /tmp/code.c

ln -sf ~/Spl/include /tmp/include
gcc -O2 -Wall /tmp/code.c -o /tmp/code -lm -lbsd

if [ -p /dev/stdin ]; then
  cat - | /tmp/code
else
  /tmp/code
fi

rm /tmp/code.c /tmp/code /tmp/include
