#!/bin/sh



infile=$(realpath "$1")
cd ~/Spl && /usr/bin/python3 splc.py "$infile" > /tmp/code.c

ln -sf ~/Spl/include /tmp/include
gcc -O2 -Wall /tmp/code.c -o /tmp/code -lm -lbsd

if [ -s /dev/stdin ]; then
  cat - | /tmp/code
else
  /tmp/code
fi

rm /tmp/code.c /tmp/code /tmp/include
