#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.asm
nasm -f elf /tmp/code.asm -o /tmp/code.o 1>&2
gcc -Wall -nostdinc -nostdinc++ -nostdlib --specs=/root/gcc.spec -m32 /tmp/code.o -o /tmp/code 1>&2

if [ -p /dev/stdin ]; then
  cat - | /tmp/code
else
  /tmp/code
fi

rm /tmp/code.asm /tmp/code.o /tmp/code
