#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
ln -sf "$infile" /tmp/A.java
cd /tmp && /usr/lib/jvm/java-1.8-openjdk/bin/javac /tmp/A.java

if [ -p /dev/stdin ]; then
  cd /tmp && (cat - | /usr/bin/java A)
else
  cd /tmp && /usr/bin/java A
fi

rm /tmp/A.java /tmp/A.class
