#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

if [ -p /dev/stdin ]; then
  cat - | ~/TrumpScript/bin/TRUMP --shut-up "$1"
else
  ~/TrumpScript/bin/TRUMP --shut-up "$1"
fi
