#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

if [ -s /dev/stdin ]; then
  cat - | mono ~/Function/Builds/Release/obj-Funciton/Funciton.exe "$1" | hexdump -Cv | sed 's/^00000000  ef bb bf//' | hexdump -R # Strip BOM
else
  mono ~/Function/Builds/Release/obj-Funciton/Funciton.exe "$1" | hexdump -Cv | sed 's/^00000000  ef bb bf//' | hexdump -R # Strip BOM
fi
