#!/bin/sh



if [ -s /dev/stdin ]; then
  cat - | mono ~/Function/Builds/Release/obj-Funciton/Funciton.exe "$1" | hexdump -Cv | sed 's/^00000000  ef bb bf//' | hexdump -R # Strip BOM
else
  mono ~/Function/Builds/Release/obj-Funciton/Funciton.exe "$1" | hexdump -Cv | sed 's/^00000000  ef bb bf//' | hexdump -R # Strip BOM
fi
