#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

/usr/bin/python ~/esotope-bfc/esotope-bfc "$1" > /tmp/code.c
gcc /tmp/code.c -s -o /tmp/code

if [ -s /dev/stdin ]; then
  cat - | /tmp/code
else
  /tmp/code
fi

rm /tmp/code.c /tmp/code
