#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

if [ -s /dev/stdin ]; then
  (cat "$1"; echo -n " "; cat -) | /usr/bin/tromp64
else
  (cat "$1"; echo -n " ") | /usr/bin/tromp64
fi
