#!/bin/sh

infile=$(realpath "$1")
ln -s "$infile" /tmp/code.tar
mkdir -p /tmp/code
tar xf /tmp/code.tar -C /tmp/code > /dev/null
cd ~/Folders/Rottytooth.Esolang.Folders/bin/Release
mono Folders.exe ../../../../../../../tmp/code > /tmp/code.cpp
g++ -Wall -O2 -std=c++11 /tmp/code.cpp -o /tmp/code.out -lm

cat - | /tmp/code.out

rm -rf /tmp/code.out /tmp/code.cpp /tmp/code.tar
