#!/bin/sh



infile=$(realpath "$1")
mkdir -p /tmp/code
tar xf "$infile" -C /tmp/code > /dev/null
cd ~/Folders/Rottytooth.Esolang.Folders/bin/Release
mono Folders.exe ../../../../../../../tmp/code 2> /dev/null

cat - | mono code.exe

rm -rf code.exe /tmp/code
