#!/bin/sh

infile=$(realpath "$1")
ln -s "$infile" /tmp/code.tar
mkdir -p /tmp/code
tar xf /tmp/code.tar -C /tmp/code > /dev/null
cd ~/Folders/Rottytooth.Esolang.Folders/bin/Release

# エラーが出るが、なんか実行される(謎)
cat - | mono Folders.exe /b /e ../../../../../../../tmp/code 2>/dev/null
# cat - | mono code.exe

rm -rf code.exe /tmp/code
