#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
mkdir -p /tmp/code
tar xf "$infile" -C /tmp/code > /dev/null
cd ~/Folders/Rottytooth.Esolang.Folders/bin/Release
mono Folders.exe ../../../../../../../tmp/code /b 2> /dev/null

if [ -p /dev/stdin ]; then
  cat - | mono code.exe
else
  mono code.exe
fi

rm -rf code.exe /tmp/code
