#!/bin/sh

infile=$(realpath "$1")
ln -s "$infile" /tmp/code.tar
mkdir -p /tmp/code
tar xf /tmp/code.tar -C /tmp/code > /dev/null
cd ~/Folders/Rottytooth.Esolang.Folders/bin/Release
mono Folders.exe ../../../../../../../tmp/code /b 1>&2

cat - | mono code.exe

rm -rf code.exe /tmp/code
