#!/bin/bash

outfile="/tmp/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1).txt"
ignore=""
ig(){ ignore="$ignore
#ifdef $1
#undef $1
#endif"; }
ig constexpr;ig const;ig char;ig in;ig out;ig f;ig int;ig main;ig std;ig ofstream;ig file;ig open;ig close;
cat <<EOF > /tmp/main.cpp
#include <fstream>
#include "code.cpp"
$ignore
constexpr const char* in = "$(cat - | hex)";
constexpr const char* out = f(in);
int main() {
	std::ofstream file;
	file.open("$outfile");
	file << out;
	file.close();
}
EOF

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.cpp

/usr/bin/clang-9 -Wall -O2 -std=c++11 /tmp/main.cpp -o /tmp/code -lm -lstdc++
/tmp/code 0<&- 1>&2

cat "$outfile"

rm -f /tmp/main.cpp /tmp/code.cpp /tmp/code "$outfile"
