#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

if [ -p /dev/stdin ]; then
  cat - | /usr/bin/node ~/MaybeLater/interpreter.js "$1"
else
  /usr/bin/node ~/MaybeLater/interpreter.js "$1" 0<&-
fi
