#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.sim
cim /tmp/code.sim -o /tmp/code >&2

if [ -p /dev/stdin ]; then
  cat - | LD_LIBRARY_PATH=/usr/local/lib /tmp/code
else
  LD_LIBRARY_PATH=/usr/local/lib /tmp/code
fi

rm /tmp/code.sim /tmp/code
