#!/bin/sh



infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.kt
cd /tmp
~/kotlinc/bin/kotlinc -include-runtime -d code.jar code.kt

cat - | /usr/bin/java -jar code.jar "$1"

rm /tmp/code.jar /tmp/code.kt
