#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
cd ~/Floater

if [ -p /dev/stdin ]; then
  cat - | /usr/bin/java -classpath src org/zomb/floater/FloaterMain "$infile"
else
  /usr/bin/java -classpath src org/zomb/floater/FloaterMain "$infile"
fi
