#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

if [ -p /dev/stdin ]; then
  cat - | /usr/bin/python ~/haystack/haystack.py "$1"
else
  /usr/bin/python ~/haystack/haystack.py "$1"
fi
