#!/bin/sh



infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.wat
/usr/bin/wat2wasm /tmp/code.wat -o /tmp/code.wasm --enable-exceptions --enable-mutable-globals --enable-saturating-float-to-int --enable-sign-extension --enable-simd --enable-threads

if [ -s /dev/stdin ]; then
  stdin=$(cat -)
else
  stdin=
fi

/usr/bin/node ~/wasm-cli.js /tmp/code.wasm "$stdin"

rm /tmp/code.wat /tmp/code.wasm
