#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.irc
ln -sf ~/irc/main.irc /tmp/main.irc
cd /tmp

if [ -p /dev/stdin ]; then
  cat - | /usr/bin/php ~/irc/irc.phps main.irc
else
  /usr/bin/php ~/irc/irc.phps main.irc
fi

rm /tmp/code.irc /tmp/main.irc
