#!/bin/sh



infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.irc
ln -sf ~/irc/main.irc /tmp/main.irc
cd /tmp

if [ -s /dev/stdin ]; then
  cat - | /usr/bin/php ~/irc/irc.phps main.irc
else
  /usr/bin/php ~/irc/irc.phps main.irc
fi

rm /tmp/code.irc /tmp/main.irc
