#!/bin/sh



if [ -s /dev/stdin ]; then
  cat - | /usr/bin/wine64 /usr/lib/wine/fakedlls/cmd.exe /Q /U /D /C "$1" | tr -d "\000"
else
  /usr/bin/wine64 /usr/lib/wine/fakedlls/cmd.exe /Q /U /D /C "$1" | tr -d "\000"
fi
