#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

if [ -p /dev/stdin ]; then
  cat - | /usr/bin/wine64 /usr/lib/wine/fakedlls/cmd.exe /Q /U /D /C "$1" | tr -d "\000"
else
  /usr/bin/wine64 /usr/lib/wine/fakedlls/cmd.exe /Q /U /D /C "$1" | tr -d "\000"
fi
