#!/bin/sh

cat - > /tmp/stdin.tex
echo "\openin0=stdin.tex" | cat - "$1" > /tmp/code.tex
cd /tmp
/usr/local/texlive/2020/bin/x86_64-linux/tex code.tex | sed -e '1,2d' | sed -e '$d' | sed -e '$d' | sed -e '$d'
rm -f code.log code.dvi code.tex stdin.tex
