#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

code=$(cat "$1")

if [ -s /dev/stdin ]; then
  input=$(cat -)
else
  input=""
fi

/usr/bin/sqlite3 ':memory:' "CREATE TABLE i (v); CREATE TABLE o (v); INSERT INTO i VALUES ('$input'); $code; SELECT v FROM o LIMIT 1;"
