#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.ll
/usr/bin/llc -filetype=obj -relocation-model=pic /tmp/code.ll -o /tmp/code.o
/usr/bin/gcc /tmp/code.o -o /tmp/code

if [ -p /dev/stdin ]; then
  cat - | /tmp/code
else
  /tmp/code
fi

rm -f /tmp/code.o /tmp/code
