#!/bin/sh

infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.ll
/usr/bin/llc -filetype=obj -relocation-model=pic /tmp/code.ll -o /tmp/code.o
/usr/bin/gcc /tmp/code.o -o /tmp/code

cat - | /tmp/code

rm -f /tmp/code.o /tmp/code
