#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

cd ~/Reverse-Programmer-Notation/lua_implementation

if [ -s /dev/stdin ]; then
  cat - | /usr/bin/lua5.3 main.lua "$1"
else
  /usr/bin/lua5.3 main.lua "$1"
fi
