#!/bin/sh

# All Emojicode code should have prefix .emojic
infile=$(realpath "$1")
ln -sf "$infile" /tmp/code.i

# ick reports wierd error when stdin is closed. We avoid it by giving empty string as input.
ick -b /tmp/code.i

cat - | /tmp/code

rm /tmp/code.i /tmp/code
