name: Test

on:
  push:
  pull_request:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest

    name: Generate matrix of tests to run

    outputs:
      affected_languages: ${{ steps.generate-matrix.outputs.affected_languages }}

    steps:
      - uses: actions/checkout@v4

      # To speed up the build, we don't use asdf to set up Ruby here.
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.2'
          bundler-cache: true

      - name: Validate docker-bake.hcl is up to date
        run: |
          ruby scripts/build.rb
          git diff --exit-code docker-bake.hcl

      - name: Get changed files
        id: list-changed-files
        uses: tj-actions/changed-files@v47.0.6

      - name: List all affected languages
        id: generate-matrix
        env:
          ALL_CHANGED_FILES: ${{ steps.list-changed-files.outputs.all_changed_files }}
        run: bundle exec ruby scripts/generate-matrix.rb

  test:
    needs: generate-matrix

    runs-on: ubuntu-latest

    name: Run tests

    strategy:
      fail-fast: false
      matrix:
        box_id: ${{fromJson(needs.generate-matrix.outputs.affected_languages)}}

    if: needs.generate-matrix.outputs.affected_languages != '[]'

    steps:
      - uses: actions/checkout@v4

      # To speed up the build, we don't use asdf to set up Ruby here.
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.2'
          bundler-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build hexagony image
        run: docker buildx bake ${{ matrix.box_id }} --load

      - name: Run hexagony tests
        run: bundle exec rspec -t box_id:${{ matrix.box_id }}
