#!/bin/sh

if [ "$#" -ne 1 ] || ! [ -e "$1" ]; then
  echo "Usage: $0 <file>" >&2
  exit 1
fi

if [ -s /dev/stdin ]; then
  input=$(cat -)
  LANG=en_US.UTF8 /usr/bin/python3 ~/emoji.py/emoji.py "$1" "$input"
else
  LANG=en_US.UTF8 /usr/bin/python3 ~/emoji.py/emoji.py "$1" 
fi
